version: "3.2"
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker-volumes/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
networks:
  demonetwork:
    driver: bridge
