version: "3.2"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker-volumes/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - demonetwork
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - demonetwork
  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - mysql
      - redis
    networks:
      - demonetwork
networks:
  demonetwork:
    driver: bridge
