// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package mysqldbmodel

import (
	"gorm.io/gorm"
)

type User struct {
	gorm.Model
	Uid      string `json:"uid"`
	Account  string `json:"account"`
	Password string `json:"password"`
}
